server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: todo-login
          uri: http://localhost:8081
          predicates:
            - Path=/login
        - id: todo-logout  
          uri: http://localhost:8081
          predicates:
            - Path=/logout
        - id: todo-static
          uri: http://localhost:8081
          predicates:
            - Path=/css/**,/js/**,/images/**,/static/**,/webjars/**
        - id: todo-api
          uri: http://localhost:8081
          predicates:
            - Path=/api/todos/**
        - id: user-api
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**
        - id: auth-api
          uri: http://localhost:8083
          predicates:
            - Path=/api/auth/**
        - id: todo-all
          uri: http://localhost:8081
          predicates:
            - Path=/**
  application:
    name: gateway-service 