server:
  port: 8081

spring:
  application:
    name: todo-service
  datasource:
    # 主数据源 - Todo数据库
    url: jdbc:mysql://localhost:3306/tododb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: false
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        enabled: true

# RestTemplate 配置
user-service:
  url: http://localhost:8082

feign:
  client:
    config:
      user-service:
        url: http://localhost:8082  # 直接指定 user-service 地址
        connect-timeout: 5000
        read-timeout: 5000
      default:
        connect-timeout: 5000
        read-timeout: 5000

logging:
  level:
    com.example.todoservice: DEBUG
    org.springframework.security: DEBUG
    org.hibernate: DEBUG
    feign: DEBUG  # 添加 Feign 调试日志
